robshakir/pyangbind

lib/yangtypes.py
Added all of the python keywords seen in the published grammar to the
reserved list: https://docs.python.org/2/reference/grammar.html
=> Add keywords from python 2.7 to reserve list

lib/base.py, lib/pybindJSON.py, lib/serialise.py, lib/xpathhelper.py, lib/yangtypes.py, pybind.py, tests/binary/run.py, tests/boolean-empty/run.py, tests/choice/run.py, tests/config-false/run.py, tests/decimal64/run.py, tests/enumeration/run.py, tests/identityref/run.py, tests/include-import/run.py, tests/int/run.py, tests/leaf-list/run.py, tests/list/run.py, tests/nested-containers/run.py, tests/openconfig-bgp-juniper/run.py, tests/serialise/json/run.py, tests/serialise/serialise_tests.sh, tests/split-classes/run.py, tests/string/run.py, tests/typedef/run.py, tests/uint/run.py, tests/union/run.py, tests/xpath/00_pathhelper_base.py, tests/xpath/01-list_leaflist/run.py, tests/xpath/02-static_ptr/run.py, tests/xpath/03-current/run.py
@vnitinv 
I propose that we merge this pull-req to support general PEP8 compliance. Commit comment below shows what is not complied with - hopefully this is something that you can set in your editor to ignore (Sublime Text 3, with SublimeLint and the PEP8 module has this ability). Comments welcome.
* As per Nitin's suggestion -- code is now mostly compliant with
the guidelines in PEP8. Exceptions:
*	Indentation is 2 spaces, not 4 (ignore: E111, E114)
* 'Natural' indentation is used for continuation (Ignore: E127,
E128)
=> Formatting fixes to support PEP8

README.md
Double quotes have been used twice, which confuses things when the
one-liner that finds the path pyangbind has been installed in. Using
single quotes for the python code avoids this.
=> Fixed quotes in example code for finding path

pyangbind/lib/yangtypes.py
Hi Rob,
Minor bug error when creating a keyed list item with a named key (key=key value) where a single key value is used, and no space character is contained in the Key Value supplied
The following worked: 
```
pybind_obj = pybindobj().somelist.add("somevalue")
pybind_obj = pybindobj().somelist.add(keyfield="some value")
pybind_obj = pybindobj().somelist.add(keyfield1="somevalue", keyfield2="somevalue")
```
The following didn't work (no space, single key, named key):
`pybind_obj = pybindobj().somelist.add(keyfield="somevalue")`
Cheers,
Mark
=> Issue when creating a list item, when a named set is used, and only one key value is supplied which doesn't contain a space

pyangbind/plugin/pybind.py, tests/int/int.yang, tests/int/run.py
Hi Rob,
As you can see from the commit comments:
> Corrected values for the ranges of signed Integer types to include the correct minimum value
> Added test case for minimum value of an integer with a restriction/range
> Added test case for 'min' alias value which is currently broken
I've included an example of a still broken case where if you specify a restriction that uses the 'min' keyword, it does not work. It's currently commented out, as it breaks the test.
```
leaf restricted-ueight-min-alias {
type int8 {
range "min..max";
}
}
```
=> Issue with Min values for Integer types with a Restriction/Range specified

pyangbind/lib/serialise.py, tests/serialise/ietf-json-deserialise/json/nonexistkey.json, tests/serialise/ietf-json-deserialise/run.py, tests/serialise/json-deserialise/json/nonexist.json, tests/serialise/json-deserialise/run.py
During deserialisation, it is sometimes advantageous to ignore keys that are unknown by the bindings, this merge adds that ability.
=> Add ability to ignore unknown keys in a JSON deserialisation

MANIFEST.in
`setup.py` references `requirements.txt` but it is not included in source tar ball. Pip install from source tar ball fails due to this.
=> Adding requirements.txt to source dist file

tests/integration/openconfig-interfaces/run.py, tests/misc/run.py, tests/presence/run.py, tests/run.sh, tests/submodules/run.py, tests/xpath/04-root/run.py, tests/xpath/xpath_tests.sh
``` 
* (M) tests/.../run.py
- Fix tests that use unittest to keep files correctly as per
#99, and building on top of solution in #100. ACK: @timmartin
* (M) tests/.../*.sh
- Fix erroneous return codes/ensure that overall test run status
is noted.
```
=> Resolve UTs not correctly keeping generated files

pyangbind/helpers/misc.py, tests/typedef/run.py, tests/typedef/typedef.yang
```
* (M) pyangbind/helpers/misc.py
- Ensure that all locations where typedefs can be scoped are
searched to define a type.
* (M) tests/typedef/
- Add unit tests to validate scoped typedefs as per bug in #98.
```
=> Add support for typedefs to be scoped.

pyangbind/lib/serialise.py, tests/integration/openconfig-bgp/run.py, tests/integration/openconfig-bgp/testdata/tc010.json, tests/integration/openconfig-bgp/testdata/tc020.json, tests/integration/openconfig-bgp/testdata/tc030.json, tests/integration/openconfig-bgp/testdata/tc040.json, tests/serialise/juniper-json-examples/run.py
```
- (M) pyangbind/lib/serialise.py:
- Ensure that decimals are properly encoded when they do not
carry specific class mapping information (fixes #109).
- (A) tests/integration/openconfig-bgp/*
- Add test cases that ensure that an OpenConfig BGP instance is
serialised as expected.
- (M) tests/integration/openconfig-interfaces/run.py
- Fix test case failure due to changes in upstream public models.
- (M) tests/serialise/juniper-json-examples/run.py
- Fix test case failure due to changes in upstream public models.
```
=> Resolve decimal serialisation issue, update for OC-BGP changes.

pyangbind/lib/serialise.py, pyangbind/lib/yangtypes.py, tests/list/run.py
I am using pyangbind to translate OpenConfig into native configuration and I am running into issues as some devices require ordering when entering IP addresses. For example, the following configuration will fail:
```
interface Ethernet2.1
encapsulation dot1q vlan 1
ip address 172.20.0.1/24 secondary
ip address 192.168.1.1/24
napalm_base.exceptions.MergeConfigException: Error [1000]: CLI command 17 of 40 'ip address 172.20.0.1/24 secondary' failed: could not run command [Primary address must be assigned first]
```
The solution is as simple as using always `OrderedDict` instead of when only `user_ordered = True`.
=> Using OrderedDict by default as some devices need ordering

pyangbind/helpers/identity.py, pyangbind/lib/pybindJSON.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, tests/binary/run.py, tests/boolean-empty/run.py, tests/choice/run.py, tests/config-false/run.py, tests/decimal64/run.py, tests/enumeration/run.py, tests/extensions/run.py, tests/identityref/run.py, tests/int/run.py, tests/leaf-list/run.py, tests/list/run.py, tests/nested-containers/run.py, tests/notification/run.py, tests/openconfig-bgp-juniper/run.py, tests/rpc/run.py, tests/split-classes/run.py, tests/string/run.py, tests/typedef/run.py, tests/uint/run.py, tests/union/run.py
This change has fixes for the basic syntax errors that occur with Python 3. I'm doing some work to make the code Python 3 compatible and this is the first step. It's not enough on its own, but merging these simple changes will mean there's less noise when applying later more involved patches.
=> Resolved simple syntax errors in Python3

pyangbind/plugin/pybind.py
Added cast to list on `known_types` and `unresolved_t` to be compatible with Python3 dictionary view functions.
=> Python3 dict keyview to list fix in pybind.

pyangbind/lib/serialise.py, tests/serialise/ietf-json-deserialise/run.py, tests/serialise/ietf-json-serialise/json/obj.json, tests/serialise/ietf-json-serialise/run.py
This intend to solve the problem observed when loading json (load_ietf_json) into an empty yang type object from a null json type value
=> Fix #151 load_ietf_json properly yang empty types

pyangbind/plugin/pybind.py, tests/base.py, tests/decimal64/run.py, tests/enumeration/run.py, tests/extensions/run.py, tests/include-import/run.py, tests/misc/run.py
Converted the following to use the new `unittest` base class:
* decimal64
* enumeration
* extensions
* include-import
* misc
I also added support in the base class for `split_class_dir` and a configurable `module_name`.
Plus, I added a file flush/fs sync when writing out the modules. This helps ensure data integrity and also prevents a timing issue we were seeing occasionally during testing. Occasionally, the tests would generate bindings, and then try to import them before the file system had synced. This would result in a module not found error.
=> More unittest conversions

pyangbind/lib/xpathhelper.py, pyangbind/lib/yangtypes.py, requirements.txt, tests/serialise/openconfig-serialise/run.py
This is some of the work done by @dbarrosop in the Python 3 compatibility effort. I've split it out in the continuing effort to trim down the scope of that PR.
I also found a couple more uses of the `re` library, which I updated to use `regex` instead.
=> Switch to using regex instead of re

pyangbind/lib/pybindJSON.py, pyangbind/lib/serialise.py, pyangbind/lib/xpathhelper.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, tests/base.py, tests/leaf-list/run.py, tests/misc/misc.yang, tests/misc/run.py, tox.ini
This will, theoretically, make strings and unicode work uniformly across Python 2 and 3. We also now properly handle utf-8 in YANG files. And in generated code files.
I also did a bit of cleaning up of imports, putting them in standard `isort` order/grouping.
And finally, I included @dbarrosop `__slots__` fixes.
=> Improve the handling of strings and unicode

pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, tests/leaf-list/run.py, tox.ini
Fixes #179 
I couldn't use the `set()` type directly due to the fact they do not maintain order. So instead, I've added a `unique=True` option, along with a uniqueness check on value assignments to `TypedList`.
=> Fixes #179: Ensure uniqueness in leaf-list

tests/integration/openconfig-interfaces/run.py
This fixes the new issues with Travis/tox builds failing.
=> Include the `openconfig-if-types.yang` in our downloads

.travis.yml, CONTRIBUTING.md, pyangbind/lib/serialise.py, tests/serialise/ietf-json-deserialise/json/complete-obj.json, tests/serialise/ietf-json-deserialise/run.py, tests/serialise/roundtrip/remote.yang, tests/serialise/roundtrip/roundtrip.yang, tests/serialise/roundtrip/run.py
```
* (M) pyangbind/lib/serialise.py
- When encountering an identityref leaf that has a prefixed
identity, strip the prefix from the value. The dictionary
that pyangbind stores internally has unprefixed, and module-prefix
prefixed paths, but rfc7951 JSON has module-name prefixed paths,
which led to #199 and #207.
- Fixes #199
- Fixes #207
* (M) tests/serialise/ietf-json-deserialise/json/complete-obj.json
* (M) tests/serialise/ietf-json-deserialise/run.py
- Update IETF JSON deserialising testdata to use prefixes.
* (A) tests/serialise/roundtrip/__init__.py
* (A) tests/serialise/roundtrip/remote.yang
* (A) tests/serialise/roundtrip/roundtrip.yang
* (A) tests/serialise/roundtrip/run.py
- Add a new roundtrip test to check we can deserialise what we
serialise. This is very simple currently to …
```
=> Fix bug whereby prefixed identityrefs were not deserialised.

pyangbind/lib/serialise.py, tests/serialise/xml-serialise/ietf-xml-serialise.yang, tests/serialise/xml-serialise/run.py
Fixes serialisation bug when an identityref leaf hasn't been assigned a value. See test case.
=> xml-serialisation: fix bug when there is an unset/missing identityref

pyangbind/lib/yangtypes.py
Collections Abstract Base Classes are deprecated since Python 3.3 and  removed in 3.10.
=> Migrate from collections to collections.abc.

.github/workflows/python-package.yml, tox.ini
This allows the CI to detect and stop breaking changes, while the known-failing tests are fixed (issues raised for that).
=> Skip known-failing tests, and block CI on fail.

pyangbind/helpers/identity.py, pyangbind/lib/base.py, pyangbind/lib/pybindJSON.py, pyangbind/lib/serialise.py, pyangbind/lib/xpathhelper.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, requirements.DEVELOPER.txt, setup.cfg, tests/__init__.py, tests/base.py, tests/extmethods/run.py, tests/identityref/run.py, tests/int/run.py, tests/leaf-list/run.py, tests/list/run.py, tests/notification/run.py, tests/serialise/ietf-json-serialise/run.py, tests/serialise/xml-serialise/run.py, tests/strings/run.py, tests/typedef/run.py, tests/uint/run.py, tests/union/run.py, tests/xpath/00_pathhelper_base.py, tests/xpath/01-list_leaflist/run.py, tox.ini
* Indicate support for updated Python3 versions.
* Remove Python2 and unittests2 dependency.
* Update version of linter black, and lint the code accordingly.
No effective changes to pyangbind code behavior of PyPi package.
=> Python version and linter updates

docs/yang.md, pyangbind/lib/serialise.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, requirements.txt, tests/binary/binary.yang, tests/binary/run.py, tests/serialise/ietf-json-deserialise/json/complete-obj.json, tests/serialise/ietf-json-deserialise/run.py, tests/serialise/ietf-json-serialise/json/obj.json, tests/serialise/ietf-json-serialise/run.py, tests/serialise/json-deserialise/json/alltypes.json, tests/serialise/json-deserialise/run.py, tests/serialise/json-serialise/json/expected-output.json, tests/serialise/json-serialise/run.py, tests/serialise/roundtrip/run.py, tests/serialise/xml-deserialise/xml/obj.xml, tests/serialise/xml-serialise/run.py, tests/serialise/xml-serialise/xml/obj.xml, tests/union/run.py, tox.ini
Hi @xavier-contreras ; @JoseIgnacioTamayo 
It's fantastic you've picked up maintenance for pyangbind! Thank you for stepping up. Now that pyangbind has a new lease of life, I'll submit a series of fixes as and when I clean them up for public consumption. If I can submit those changes in a way that make it easier for you to review, please tell me.
This first set included here fixes representation of the `binary` built-in type. It also fixes the unit-tests by pinning the version of YANG models to a known passing version. (In fact, my opinion is that the YANG models we use should be committed to the repo, instead of fetching them over the network on every run. I can make that change if you agree.) The UT pass on python3.9. I removed python2.7 as I'm pretty sure my usage of `super()` won't …
=> Fix binary type representation

.github/workflows/pypi.yml
I forgot that 'build' package needs to be installed in the GitHub Action environment.
=> Add step to install build for GithubAction

pyangbind/lib/serialise.py, tests/identityref/run.py
This is a rebase of @markuscraig's PR #213 over the most recent master (original PR has a conflict when rebasing), plus a testcase that exhibits the issue.
Without the fix, testcase `test_json_ietf_serialise_namespace_handling_remote` fails with:
```
>               self.assertEqual(
data["identityref:ietfint"]["ref"],
"remote-two:remote-id",
)
E               AssertionError: 'remote-two:remote-two:remote-id' != 'remote-two:remote-id'
E               - remote-two:remote-two:remote-id
E               ? -----------
E               + remote-two:remote-id
```
Reference: https://www.ietf.org/rfc/rfc6020.txt sections 9.10.*
=> Don't prefix a property value that is already prefixed

docs/yang.md, pyangbind/lib/serialise.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, tests/bits/bits.yang, tests/bits/run.py, tests/serialise/json-deserialise/json-deserialise.yang, tests/serialise/json-deserialise/json/alltypes.json, tests/serialise/json-deserialise/run.py, tests/serialise/json-serialise/json-serialise.yang, tests/serialise/json-serialise/json/expected-output.json, tests/serialise/json-serialise/run.py, tests/serialise/xml-deserialise/ietf-xml-deserialise.yang, tests/serialise/xml-deserialise/xml/obj.xml, tests/serialise/xml-serialise/ietf-xml-serialise.yang, tests/serialise/xml-serialise/run.py, tests/serialise/xml-serialise/xml/obj.xml
The YANG "bits" type gets mapped to a `Set[str]` object in Python. The set object is augmented with a dictionary keeping track of the bit positions. This is used when forming the JSON or XML serialisation.
closes https://github.com/robshakir/pyangbind/issues/314
=> Handle the "bits" type

pyangbind/plugin/pybind.py
This is an improvement by a colleague of mine, @jamie01
pyangbind was taking around 18 seconds on my machine to create the classes for the collection of YANG models for a proprietary routing device. After doing some profiling, deepcopy operations were by far the worst offenders and in particular the deepcopy of "class_map" - a large structure containing all the yang types seen along the way.
Since the copied var doesn't modify deeply nested data, swapping it for a copy seemed reasonable. If I diff the python output file from deepcopy vs copy the files are identical. And not only that, the whole process now completes in under 4 seconds.
=> Optimisation: change class_map deepcopy to copy

.github/workflows/python-test.yml, .gitignore, scripts/release.sh
Add Jobs to the GitHub Action, to test that building and using the package with pyang works properly.
This is intended to discover issues not seen with tox unit tests.
Also, this installs all dependencies of pyangbind for different python versions.
=> Add GitHub Action to build and bind with pyang

pyangbind/plugin/pybind.py, tests/config-false/run.py
Rebase of #222 over latest master. Dropped the UT change, and applied a review suggestion to use a temporary var to avoid fetching the same value twice. Original author is @nicolasmorini .
When a YANG definition of a container has the statement "config false;", the Python bindings generated for this container should have "is_config=False" in its __init__ method, but it was not the case.
Containers nested in non-config containers correctly inherited the _is_config attribute from its parent.
Add two test cases to tests/config-false.
=> Fix _is_config attribute for non-config containers

pyangbind/helpers/identity.py, tests/identityref/run.py
Rebase of #220 over latest master, plus UT for the issue fixed here.
=> Fix missing identityref namespace

docs/usage.md
Pyangbind `--use-xpath-helper` is incorrectly mentioned in the usage documentation. The actual option is `--use-xpathhelper`. See implementation: https://github.com/robshakir/pyangbind/blob/88db69c17f551122e842952fd1b4a0eac710f253/pyangbind/plugin/pybind.py#L228
Also in xpathhelper docs the option is correctly named: https://github.com/robshakir/pyangbind/blob/88db69c17f551122e842952fd1b4a0eac710f253/docs/xpathhelper.md?plain=1#L62
=> docs: fix --use-xpathhelper usage

pyangbind/helpers/misc.py, pyangbind/lib/pybindJSON.py, pyangbind/lib/serialise.py, pyangbind/lib/xpathhelper.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py
Simply run black to lint the project.
=> Let black format some files.

pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, tests/presence/presence.yang, tests/presence/run.py
Likely solves https://github.com/robshakir/pyangbind/issues/336
- Correct encoding of a model instance after a presence container was set/unset.
- Generate correct python code with SplitClassDir option, when the model has Presence containers
- Render correctly Presence containers using groupings
=> Fix presence with SplitClassDir option, and containing Groups

pyangbind/lib/yangtypes.py, tests/serialise/xml-deserialise/ietf-xml-deserialise.yang, tests/serialise/xml-deserialise/xml/obj.xml
A fix for https://github.com/robshakir/pyangbind/issues/345
When decoding an XML blob, pyanbind was trying to check the pattern restriction on an lxml.objectify.StringElement object, which is not a native string type. 
With JSON decoding, this problem does not happen because the JSON value is a native str type.
=> Fix decoding xml blob with key that must follow a pattern

README.md
This should fix what i think it's a typo as `next-hops` is a container of the list `next-hop`
=> fix: readme next-hop typo

.coveragerc, pyangbind/lib/pybindJSON.py, pyangbind/lib/serialise.py, pyangbind/lib/xpathhelper.py, pyangbind/lib/yangtypes.py, pyangbind/plugin/pybind.py, requirements.txt, tests/misc/run.py, tests/serialise/ietf-json-serialise/run.py, tests/serialise/json-serialise/run.py, tests/serialise/xml-serialise/run.py, tests/union/run.py, tox.ini
Because there is only Python3 now
=> Remove six

pyangbind/plugin/pybind.py
=> Fix Python header formatting
