- pyangbind/lib/serialise.py
- pyangbind/lib/yangtypes.py
- pyangbind/plugin/pybind.py
- tests/identityref/identityref.yang
- tests/identityref/run.py
Resolve #41 whereby inheritance of identity values was not implemented.
> Resolve identityref inheritance issue in #41

- pyangbind/lib/yangtypes.py
- pyangbind/plugin/pybind.py
- tests/config-false/run.py
I've added support for nodes to report whether they are configurable, with a field called `_is_config`. See #52.
> Nodes now report whether they are configurable

- pyangbind/lib/serialise.py
- pyangbind/lib/xpathhelper.py
- setup.py
- tests/decimal64/run.py
- ignore RestrictedPrecisionDecimal
- raise more specific "not found" in xpathhelper
- set zip_safe=False (plugin won't be found by pyang otherwise)
> Minor fixes

- pyangbind/lib/yangtypes.py
- pyangbind/plugin/pybind.py
- tests/int/int.yang
- tests/int/run.py
- tests/uint/run.py
* Merge @mpainenz contribution to fix integer ranges which were incorrectly specified.
* Add new unit tests for integer types to do bounds checking.
* Fix some formatting issues in pybind.py.
> Ref #61: Merge Integer Range Fixes

- .gitignore
- pyangbind/plugin/pybind.py
- tests/notification/notification.yang
- tests/notification/run.py
Hi Rob,
I added support for YANG notifications to PyangBind and the related test unit.
Please, take a look and let me know if there is something missing/incorrect.
Best,
Lluis
> Added support for YANG Notifications and the related test unit.

- pyangbind/lib/serialise.py
- pyangbind/lib/xpathhelper.py
Merge miscellaneous bug fixes.
> Misc. bugfixes to be rebased

- README.md
Updated print statement to allow for python3 execution
> Updated PYBINDPLUGIN path determination to allow for python2 and python3 execution

- tests/int/run.py
Given the size of this test file, I'm opening this as an independent PR
> Convert the int tests to unittest

- tests/serialise/ietf-json-serialise/run.py
- tests/serialise/json-deserialise/run.py
- tests/serialise/json-serialise/run.py
This includes the following:
* ietf-json-serialise
* json-deserialise
* json-serialise
> Half of the serialise tests converted to unittest

- pyangbind/lib/pybindJSON.py
- tests/__init__.py
- tests/base.py
- tests/serialise/ietf-json-deserialise/run.py
- tests/serialise/ietf-json-serialise/run.py
- tests/serialise/json-deserialise/run.py
- tests/serialise/json-serialise/run.py
- tests/serialise/juniper-json-examples/run.py
- tests/serialise/openconfig-serialise/run.py
I also fixed an issue with loading the auto-generated modules via `importlib`. Apparently, there is a module cache which I wasn't clearing out.
> Converted the last of the serialise tests to unittest

- .gitignore
- tests/base.py
- tests/integration/openconfig-bgp/run.py
- tests/integration/openconfig-interfaces/run.py
In addition:
* Updated the .gitignore to include a whole lot more (Largely from github's template)
* Added more cleanup of `sys.modules` necessary for proper use of importlib.
> Convert integration tests to use unittest

- tests/config-false/run.py
- tests/identityref/run.py
This one converts the `config-false` and `identityref` tests to use unittest
> More unittest conversions

- .gitignore
- tests/base.py
- tests/extmethods/run.py
- tests/notification/run.py
- tests/presence/run.py
- tests/split-classes/run.py
This one converted the following tests to use unittest:
* extmethods
* notification
* presence
* split-classes
I also discovered a super simple bug that had me wanting to smash my head on the desk. 😄
> Converted more tests to unittest, and fixed a silly bug

- tests/xpath/01-list_leaflist/run.py
This was a large enough change that it seemed to warrant its own pull request.
I eliminated a number of assertions from `t5` which appeared to be duplicates of assertions in `t3`, since both were directly referencing a `leaf-list <x> { type string; }` and not testing any of the pointers to those leaf-lists.
> Convert the xpath 01 tets to use unittest

- tests/list/run.py
After a full day of work, it is finally done! Talk about a beast.
This makes for 266 tests, and 74% test coverage! :tada:
> Convert the list tests to use unittest

- tests/rpc/run.py
This one was much easier than I expected. Especially after tackling the list tests...
> Convert the RPC tests to use unittest

- README.md
- docs/serialisation.md
Just some updates to the docs. I think we can say XML serialisation/deserialisation is _supported_ now.
> xml-serialisation: small docs update

- .github/workflows/python-package.yml
Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
> Adding GitHub Action to test and package pyangbind

- tests/serialise/openconfig-serialise/json/interfaces_ph:False-flt:False-m:default.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:False-flt:False-m:ietf.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:True-flt:False-m:default.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:True-flt:False-m:ietf.json
New leaf 'resets' was added in commit https://github.com/openconfig/public/commit/face342aaf2f65988b1bbd21a08faee72ec0d736
> Update after openconfig-interfaces changes

- pyangbind/plugin/pybind.py
- tests/union/union.yang
Fix for https://github.com/robshakir/pyangbind/issues/317
> set tuple for default value on union typedef

- .github/workflows/pypi.yml
- .github/workflows/python-test.yml
- scripts/release.sh
- setup.cfg
- tox.ini
Intended to prevent https://github.com/robshakir/pyangbind/issues/324 from happening on next releases
> Fix release automation

- tests/serialise/openconfig-serialise/json/interfaces_ph:False-flt:False-m:default.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:False-flt:False-m:ietf.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:True-flt:False-m:default.json
- tests/serialise/openconfig-serialise/json/interfaces_ph:True-flt:False-m:ietf.json
Changes after https://github.com/openconfig/public/pull/947
> Update oc-interface json blobs.

- pyangbind/helpers/identity.py
- tests/identityref/identityref.yang
- tests/identityref/run.py
Possible fix for https://github.com/robshakir/pyangbind/issues/348
Fork of https://github.com/robshakir/pyangbind/pull/248
> Dimbleby multiple bases
